language: node_js
node_js:
  - "12"
branches:
  only:
    - master
install:
  - yarn
script:
  - yarn build
  - node ./__selenium/basic-test.js
addons:
  browserstack:
    username: emresakarya1
    access_key:
      secure: lQQQ1/1uGTGNdYN+KvQ70QXA+tWoVnDL6DdWR7GL9jZoQoP2REX7vQDNuApr4deqbpsfw5kk6hDtRcdacoHz49Qi7mmWdVi1HaasY18F9n2Md5Kp+Uw8EbRYcKQcRtmz1E+o1ieVa0Ua9LO9W4dV25UieYeXGPhEYwyHg44yOBWeZzZZyXxbRYMC+06FXrjiQ+41YqZSNsBxg5AbezAbEEobl8QhMuDPtOA7JfFcC2r/63T+mcq57+s4ioF4JHLROHOGl7s7Evu1gRbjhQRr572d5dnsFI1TVgtdMlf6MBeDUJVKHUSS5BfGvjYUHAVtS+UXW9LD+5JKJW2MaiKGw1lr02YGyHMZTVDufUW8AEBJGKFOgp0Fd8KKByCDxcSU+QsJyFCJYOYeaq+jhirxl1whoOHOIHROowsKBetAgUksJCP94elu466v7zZXv+RA4A2NYx7JsOya/6LF9lDrpssunedWrBNkHbRGiSivIxxNYN/jLz5EK1QqCrRxIrVY2sQs/sAue5dIpfGH+Q0KOLzbGvgHEKzT6sqpD+CoFE0eRK/Fmu1eW/oHLCn4Pt+HcRXsROtZ1qJRBdRuNcuV8wDrobydCWRZiGcwUpA06TKcIgYMoHrhlFXScOf56vaDbmonPQERbYHBDj2Wsj7956rH5jOB+kK8SaTvOcAGxls=
