language: node_js
node_js:
  - "12"
branches:
  only:
    - master
install:
  - yarn
script:
  - yarn build
  - yarn win10-firefox-2
  - yarn osCatalinaSafari-13
  - yarn win8-chrome-2
  - yarn win8.1-edge-2
  - yarn win7-IE11
